[build]
  publish = "."

[[redirects]]
  from = "/app/*"
  to = "/hub"
  status = 301

[[redirects]]
  from = "/blog/"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/blog"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/blog.html"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/about.html"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/shop.html"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/about"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/shop"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/about/*"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/shop/*"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/about-us"
  to = "/"
  status = 410
  force = true

[[redirects]]
  from = "/about-us/*"
  to = "/"
  status = 410
  force = true
